---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typeclaw-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - typeclaw.fml09.io
  resources:
  - credentialapprovals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - typeclaw.fml09.io
  resources:
  - credentialrequests
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - typeclaw.fml09.io
  resources:
  - credentialrequests/status
  - typeclawinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - typeclaw.fml09.io
  resources:
  - typeclawinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - typeclaw.fml09.io
  resources:
  - typeclawinstances/finalizers
  verbs:
  - update
