//go:build !ignore_autogenerated

/*
Copyright 2026 the TypeClaw Operator authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoUpdateSpec) DeepCopyInto(out *AutoUpdateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoUpdateSpec.
func (in *AutoUpdateSpec) DeepCopy() *AutoUpdateSpec {
	if in == nil {
		return nil
	}
	out := new(AutoUpdateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSpec) DeepCopyInto(out *BackupSpec) {
	*out = *in
	in.SnapshotVolume.DeepCopyInto(&out.SnapshotVolume)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSpec.
func (in *BackupSpec) DeepCopy() *BackupSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStatus) DeepCopyInto(out *BackupStatus) {
	*out = *in
	if in.LastSnapshotTime != nil {
		in, out := &in.LastSnapshotTime, &out.LastSnapshotTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStatus.
func (in *BackupStatus) DeepCopy() *BackupStatus {
	if in == nil {
		return nil
	}
	out := new(BackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialApproval) DeepCopyInto(out *CredentialApproval) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialApproval.
func (in *CredentialApproval) DeepCopy() *CredentialApproval {
	if in == nil {
		return nil
	}
	out := new(CredentialApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialApproval) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialApprovalList) DeepCopyInto(out *CredentialApprovalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CredentialApproval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialApprovalList.
func (in *CredentialApprovalList) DeepCopy() *CredentialApprovalList {
	if in == nil {
		return nil
	}
	out := new(CredentialApprovalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialApprovalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialApprovalSpec) DeepCopyInto(out *CredentialApprovalSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialApprovalSpec.
func (in *CredentialApprovalSpec) DeepCopy() *CredentialApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialConsumerSpec) DeepCopyInto(out *CredentialConsumerSpec) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]CredentialOperation, len(*in))
		copy(*out, *in)
	}
	if in.AllowedRepositories != nil {
		in, out := &in.AllowedRepositories, &out.AllowedRepositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialConsumerSpec.
func (in *CredentialConsumerSpec) DeepCopy() *CredentialConsumerSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialConsumerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialPolicySpec) DeepCopyInto(out *CredentialPolicySpec) {
	*out = *in
	out.Secret = in.Secret
	if in.Consumers != nil {
		in, out := &in.Consumers, &out.Consumers
		*out = make([]CredentialConsumerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialPolicySpec.
func (in *CredentialPolicySpec) DeepCopy() *CredentialPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CredentialPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRequest) DeepCopyInto(out *CredentialRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRequest.
func (in *CredentialRequest) DeepCopy() *CredentialRequest {
	if in == nil {
		return nil
	}
	out := new(CredentialRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRequestList) DeepCopyInto(out *CredentialRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CredentialRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRequestList.
func (in *CredentialRequestList) DeepCopy() *CredentialRequestList {
	if in == nil {
		return nil
	}
	out := new(CredentialRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CredentialRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRequestSpec) DeepCopyInto(out *CredentialRequestSpec) {
	*out = *in
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
	out.SecretBinding = in.SecretBinding
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRequestSpec.
func (in *CredentialRequestSpec) DeepCopy() *CredentialRequestSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRequestStatus) DeepCopyInto(out *CredentialRequestStatus) {
	*out = *in
	if in.TicketConsumedAt != nil {
		in, out := &in.TicketConsumedAt, &out.TicketConsumedAt
		*out = (*in).DeepCopy()
	}
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = new(GitHubIssueResult)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRequestStatus.
func (in *CredentialRequestStatus) DeepCopy() *CredentialRequestStatus {
	if in == nil {
		return nil
	}
	out := new(CredentialRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialSecretRef) DeepCopyInto(out *CredentialSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialSecretRef.
func (in *CredentialSecretRef) DeepCopy() *CredentialSecretRef {
	if in == nil {
		return nil
	}
	out := new(CredentialSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubCreateIssueSpec) DeepCopyInto(out *GitHubCreateIssueSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubCreateIssueSpec.
func (in *GitHubCreateIssueSpec) DeepCopy() *GitHubCreateIssueSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubCreateIssueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubIssueResult) DeepCopyInto(out *GitHubIssueResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubIssueResult.
func (in *GitHubIssueResult) DeepCopy() *GitHubIssueResult {
	if in == nil {
		return nil
	}
	out := new(GitHubIssueResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	if in.IngressCIDRs != nil {
		in, out := &in.IngressCIDRs, &out.IngressCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopAccessSpec) DeepCopyInto(out *PersonalDesktopAccessSpec) {
	*out = *in
	if in.Tailscale != nil {
		in, out := &in.Tailscale, &out.Tailscale
		*out = new(PersonalDesktopTailscaleAccessSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopAccessSpec.
func (in *PersonalDesktopAccessSpec) DeepCopy() *PersonalDesktopAccessSpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopGatewaySpec) DeepCopyInto(out *PersonalDesktopGatewaySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopGatewaySpec.
func (in *PersonalDesktopGatewaySpec) DeepCopy() *PersonalDesktopGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopImageImportSpec) DeepCopyInto(out *PersonalDesktopImageImportSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopImageImportSpec.
func (in *PersonalDesktopImageImportSpec) DeepCopy() *PersonalDesktopImageImportSpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopImageImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopImageSpec) DeepCopyInto(out *PersonalDesktopImageSpec) {
	*out = *in
	if in.Import != nil {
		in, out := &in.Import, &out.Import
		*out = new(PersonalDesktopImageImportSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopImageSpec.
func (in *PersonalDesktopImageSpec) DeepCopy() *PersonalDesktopImageSpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopLinuxSpec) DeepCopyInto(out *PersonalDesktopLinuxSpec) {
	*out = *in
	if in.SSHAuthorizedKeys != nil {
		in, out := &in.SSHAuthorizedKeys, &out.SSHAuthorizedKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopLinuxSpec.
func (in *PersonalDesktopLinuxSpec) DeepCopy() *PersonalDesktopLinuxSpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopLinuxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopOwnerSpec) DeepCopyInto(out *PersonalDesktopOwnerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopOwnerSpec.
func (in *PersonalDesktopOwnerSpec) DeepCopy() *PersonalDesktopOwnerSpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopOwnerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopResourcesSpec) DeepCopyInto(out *PersonalDesktopResourcesSpec) {
	*out = *in
	out.Memory = in.Memory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopResourcesSpec.
func (in *PersonalDesktopResourcesSpec) DeepCopy() *PersonalDesktopResourcesSpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopResourcesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopRootVolumeSpec) DeepCopyInto(out *PersonalDesktopRootVolumeSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopRootVolumeSpec.
func (in *PersonalDesktopRootVolumeSpec) DeepCopy() *PersonalDesktopRootVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopRootVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopScreenSpec) DeepCopyInto(out *PersonalDesktopScreenSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopScreenSpec.
func (in *PersonalDesktopScreenSpec) DeepCopy() *PersonalDesktopScreenSpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopScreenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopSpec) DeepCopyInto(out *PersonalDesktopSpec) {
	*out = *in
	out.Owner = in.Owner
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = new(PersonalDesktopAccessSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Image.DeepCopyInto(&out.Image)
	in.RootVolume.DeepCopyInto(&out.RootVolume)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Screen != nil {
		in, out := &in.Screen, &out.Screen
		*out = new(PersonalDesktopScreenSpec)
		**out = **in
	}
	if in.Linux != nil {
		in, out := &in.Linux, &out.Linux
		*out = new(PersonalDesktopLinuxSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Windows != nil {
		in, out := &in.Windows, &out.Windows
		*out = new(PersonalDesktopWindowsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(PersonalDesktopGatewaySpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopSpec.
func (in *PersonalDesktopSpec) DeepCopy() *PersonalDesktopSpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopStatus) DeepCopyInto(out *PersonalDesktopStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopStatus.
func (in *PersonalDesktopStatus) DeepCopy() *PersonalDesktopStatus {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopTailscaleAccessSpec) DeepCopyInto(out *PersonalDesktopTailscaleAccessSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedLogins != nil {
		in, out := &in.AllowedLogins, &out.AllowedLogins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopTailscaleAccessSpec.
func (in *PersonalDesktopTailscaleAccessSpec) DeepCopy() *PersonalDesktopTailscaleAccessSpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopTailscaleAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopWindowsInstallerSpec) DeepCopyInto(out *PersonalDesktopWindowsInstallerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopWindowsInstallerSpec.
func (in *PersonalDesktopWindowsInstallerSpec) DeepCopy() *PersonalDesktopWindowsInstallerSpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopWindowsInstallerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalDesktopWindowsSpec) DeepCopyInto(out *PersonalDesktopWindowsSpec) {
	*out = *in
	if in.PythonInstaller != nil {
		in, out := &in.PythonInstaller, &out.PythonInstaller
		*out = new(PersonalDesktopWindowsInstallerSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalDesktopWindowsSpec.
func (in *PersonalDesktopWindowsSpec) DeepCopy() *PersonalDesktopWindowsSpec {
	if in == nil {
		return nil
	}
	out := new(PersonalDesktopWindowsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeSpec) DeepCopyInto(out *RuntimeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeSpec.
func (in *RuntimeSpec) DeepCopy() *RuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySpec) DeepCopyInto(out *SecuritySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySpec.
func (in *SecuritySpec) DeepCopy() *SecuritySpec {
	if in == nil {
		return nil
	}
	out := new(SecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfConfigSpec) DeepCopyInto(out *SelfConfigSpec) {
	*out = *in
	if in.ProtectedPaths != nil {
		in, out := &in.ProtectedPaths, &out.ProtectedPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfConfigSpec.
func (in *SelfConfigSpec) DeepCopy() *SelfConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SelfConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfConfigStatus) DeepCopyInto(out *SelfConfigStatus) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.ChangedPaths != nil {
		in, out := &in.ChangedPaths, &out.ChangedPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfConfigStatus.
func (in *SelfConfigStatus) DeepCopy() *SelfConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SelfConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	in.AgentFolder.DeepCopyInto(&out.AgentFolder)
	if in.RuntimeHome != nil {
		in, out := &in.RuntimeHome, &out.RuntimeHome
		*out = new(VolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeClawInstance) DeepCopyInto(out *TypeClawInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeClawInstance.
func (in *TypeClawInstance) DeepCopy() *TypeClawInstance {
	if in == nil {
		return nil
	}
	out := new(TypeClawInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TypeClawInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeClawInstanceList) DeepCopyInto(out *TypeClawInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TypeClawInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeClawInstanceList.
func (in *TypeClawInstanceList) DeepCopy() *TypeClawInstanceList {
	if in == nil {
		return nil
	}
	out := new(TypeClawInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TypeClawInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeClawInstanceSpec) DeepCopyInto(out *TypeClawInstanceSpec) {
	*out = *in
	out.Runtime = in.Runtime
	in.Storage.DeepCopyInto(&out.Storage)
	if in.ExposeTUI != nil {
		in, out := &in.ExposeTUI, &out.ExposeTUI
		*out = new(bool)
		**out = **in
	}
	if in.RestartRelay != nil {
		in, out := &in.RestartRelay, &out.RestartRelay
		*out = new(bool)
		**out = **in
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoUpdate != nil {
		in, out := &in.AutoUpdate, &out.AutoUpdate
		*out = new(AutoUpdateSpec)
		**out = **in
	}
	in.Network.DeepCopyInto(&out.Network)
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecuritySpec)
		**out = **in
	}
	if in.SelfConfig != nil {
		in, out := &in.SelfConfig, &out.SelfConfig
		*out = new(SelfConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialPolicy != nil {
		in, out := &in.CredentialPolicy, &out.CredentialPolicy
		*out = new(CredentialPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PersonalDesktop != nil {
		in, out := &in.PersonalDesktop, &out.PersonalDesktop
		*out = new(PersonalDesktopSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeClawInstanceSpec.
func (in *TypeClawInstanceSpec) DeepCopy() *TypeClawInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(TypeClawInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeClawInstanceStatus) DeepCopyInto(out *TypeClawInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(UpdateStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.SelfConfig != nil {
		in, out := &in.SelfConfig, &out.SelfConfig
		*out = new(SelfConfigStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PersonalDesktop != nil {
		in, out := &in.PersonalDesktop, &out.PersonalDesktop
		*out = new(PersonalDesktopStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeClawInstanceStatus.
func (in *TypeClawInstanceStatus) DeepCopy() *TypeClawInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(TypeClawInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStatus) DeepCopyInto(out *UpdateStatus) {
	*out = *in
	if in.ConfirmationDeadline != nil {
		in, out := &in.ConfirmationDeadline, &out.ConfirmationDeadline
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStatus.
func (in *UpdateStatus) DeepCopy() *UpdateStatus {
	if in == nil {
		return nil
	}
	out := new(UpdateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeClaimSpec) DeepCopyInto(out *VolumeClaimSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeClaimSpec.
func (in *VolumeClaimSpec) DeepCopy() *VolumeClaimSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeClaimSpec)
	in.DeepCopyInto(out)
	return out
}
