apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/typeclaw.fml09.io_typeclawinstances.yaml
  - bases/typeclaw.fml09.io_credentialrequests.yaml
  - bases/typeclaw.fml09.io_credentialapprovals.yaml
